"""
Stable finding code strings for structural Validate.

Internal module — not re-exported from package ``__init__``.
"""

EMPTY_PLAN = "EMPTY_PLAN"
DUPLICATE_STEP_ID = "DUPLICATE_STEP_ID"
UNKNOWN_DEPENDENCY = "UNKNOWN_DEPENDENCY"
SELF_DEPENDENCY = "SELF_DEPENDENCY"
DEPENDENCY_CYCLE = "DEPENDENCY_CYCLE"
DUPLICATE_DEPENDENCY = "DUPLICATE_DEPENDENCY"
REDUNDANT_DEPENDENCY = "REDUNDANT_DEPENDENCY"
ISOLATED_STEP = "ISOLATED_STEP"
DISCONNECTED_GRAPH = "DISCONNECTED_GRAPH"
IRREVERSIBLE_NO_OUTCOME = "IRREVERSIBLE_NO_OUTCOME"
PRECONDITION_NOT_IN_DEPENDS_ON = "PRECONDITION_NOT_IN_DEPENDS_ON"
MISSING_TERMINAL_OUTCOME = "MISSING_TERMINAL_OUTCOME"
